### ISSUE TITLE
데이터베이스에서 기본 키를 지정하도록 변경

### ISSUE THREAD

**Issue by Asyvix** [hank-dohwankim/Vue.js-.NET_Core_3.1-Template#4]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
애트리뷰트를 이용하여 명시적으로 설정이 가능합니다.

예를들면 1~10번까지의 데이터가 데이터베이스에 있었는데
6번데이터가 사라졌다면, 데이터베이스는 6번을 키로 재활용할 수 있게 됩니다.

**Comment by hank-dohwankim** [comment]
감사합니다. 말씀해주신 내용을 보고 몰랐던 DatabaseGenerated 애트리뷰트에 대해서 공부하게 되었습니다. 

한 가지 여쭤볼것이 생겼는데, DatabaseGeneratedOption.None 의 사용예에 대한 질문입니다. 정확히는 Key값에 DatabaseGeneratedOption.None를 사용하는 예시를 봤는데, None을 사용하는 이유에 대해 정확한 이유가 궁금합니다.

Computed, Identity, None 3가지 옵션이 있는것을 보았는데, 실제 사용 예를 찾아보다가 

1. Identity는 최초 입력되는 데이터 ex) DateTime CreatedDate
2. Computed 는 입력/업데이트 되는 데이터 ex) DateTime UpdatedDate
3. None은 Id값 ex) int postId 

이런식으로 사용되는걸 보았습니다. 2,3번은 납득이 가는데 1번은 좀 Identity 쓰는게 아닌가 조금 의문이 들었었습니다. 일단 지금은 Entity Framework에서 int값은 자동으로 PK로 설정 하는데 그걸 덮어쓰지 않으려고 None으로 한다고 이해는 하고 있습니다. 혹시 제가 제대로 이해하고 있는게 맞는지 여쭤보고 싶습니다.

**Comment by hank-dohwankim** [comment]
감사합니다. 말씀해주신 내용을 보고 몰랐던 DatabaseGenerated 애트리뷰트에 대해서 공부하게 되었습니다.

한 가지 여쭤볼것이 생겼는데, DatabaseGeneratedOption.None 의 사용예에 대한 질문입니다. 정확히는 Key값에 DatabaseGeneratedOption.None를 사용하는 예시를 봤는데, PK가 되는 Key값에 None 옵션을 사용하는 이유가 궁금합니다.

Computed, Identity, None 3가지 옵션이 있는것을 보았고, 실제 사용 예를 찾아보다가

1. Identity는 최초 입력되는 데이터 ex) DateTime CreatedDate
2. Computed 는 입력/업데이트 되는 데이터 ex) DateTime UpdatedDate
3. None은 Id값 ex) int postId

이런식으로 사용되는걸 보았습니다. 1,2번은 납득이 가는데 3번은 Identity 쓰는게 맞지 않나 하는 의문이 들었었습니다. 현재까지 알아본 내용으로는 Entity Framework에서 int값은 자동으로 PK로 설정 하는데 그걸 덮어쓰지 않으려고 None으로 한다고 이해를 하고 있습니다. 혹시 제가 제대로 이해하고 있는게 맞는지 여쭤보고 싶습니다.

**Comment by Asyvix** [comment]
@hank-dohwankim 
Identity 는 최초 입력될 때 "데이터베이스" 가 키 값을 지정하도록 합니다.
Computed는 최초 입력/데이터가 업데이트 될 때  "데이터베이스" 가 값을 업데이트합니다.
None는 어느 상황에서도 "데이터베이스" 는 데이터에 관여하지 않습니다.

즉 None는 직접 값을 지정해주고 싶을때 사용하는것입니다.
DatabaseGeneratedOption 애트리뷰트를 붙이지 않았을 때를 생각하시면 됩니다.
다만 있는 이유는 명시적으로 데이터베이스가 값을 생성하지 않음을 선언해주고싶을때 쓰시면 됩니다.

이런게 있는 이유는 우선 EntityFramework의 정의를 고려해봐야 합니다.
엔티티 프레임워크는 모든게 관리되는 ORM이자 데이터베이스 커넥터입니다.
이런 목적은 최근에 EntityFramwork에서 직접적인 SQL구문 삽입을 막았다는것에서 볼 수 있는데, 엔티티 프레임워크 자체에서도 캐시를 가지고 데이터를 관리하기때문에 데이터베이스의 상태는 엔티티프레임워크 단에서 모든걸 관리해야 하기 때문입니다.
그런 도중 감시가 어려운 사용자의 직접 쿼리를 막기 위함이죠.

그리고 이런 "데이터베이스와 크게 묶이지 않은 추상적인"기능들을 구현한 대표적인 기술이
Code First 데이터베이스 모델입니다.

우리는 데이터베이스가 어떻게 작동하는지 몰라도 엔티티 프레임워크와 그 구현체가 알아서 분석하여 데이터베이스에 알맞는 타입으로 변환시켜주는것이죠.

이렇게되면 분명 개발자는 데이터베이스를 깊게 알지 못해도 CRUD작업이 가능해지기때문에 매우 편리합니다. 따로 데이터베이스 관리자를 둘 필요도 없으니 정말 편하구요.

다만 단점으로는 데이터베이스의 고유 기능을 사용하지 못하게 된다는것입니다.
예를들어 Postgresql의 트리거 기능같은 기능 말이죠. 이외에도 자체적인 PK최적화나 인덱싱에도 어려움을 겪을 수밖에 없습니다.

그래서 이런 문제를 해결하면서도 여전히 데이터베이스 자체와는 느슨한 관계를 유지하기 위해
여러 애트리뷰트들이 붙습니다.
예로 Key는 데이터베이스에서 해당 프로퍼티를 PK로 지정하도록 명시적으로 선언하며
DatabaseGeneratedOption은 데이터베이스의 PK관리기능이나 기타 데이터 자동 변경 기능을
"느슨하게"호출하도록 도와줍니다.

이런 이유로 EF에 추가되는 여러가지 애트리뷰트들이 있고 이를통해 개발자는 데이터베이스를 몰라도 나름대로 데이터베이스의 고유 기능을 잘 사용할 수 있게 되는것이죠.

**Comment by Asyvix** [comment]
제가썻지만 잘쓴것같네요.

**Comment by hendrik-kim** [comment]
선생님의 박식함에 감탄을 금할 수가 없습니다.
